#include "tlpp-core.th"
#include "tlpp-rest.th"
 
// Chamada: http://localhost:9090/api/testDeleteKeyHeader
@Get("testDeleteKeyHeader")
User Function DeleteKeyHeaderExample()
 
Local cRet := "Fail"
 
oRest:setKeyHeaderResponse("Allow", "metodos_permitidos")
 
If !Empty(oRest:getKeyHeaderResponse("Allow"))
     
    oRest:deleteKeyHeaderResponse("Allow")
     
    cRet := "Header criado, lido e depois deletado com sucesso!"
 
EndIf
 
oRest:setResponse(cRet)
 
 
Return .T.
