#include "tlpp-core.th"
#include "tlpp-rest.th"
 
@Get('/documentation/getThreadPoolName')
User Function fGetThreadPoolName()
 
Local cResponse := ""
Local cRet      := oRest:getThreadPoolName()
 
If (ValType(cRet) == 'C')
    cResponse := '{"getThreadPoolName": "Nome do threadpool: ' + cRet + '"}'
Else
    cResponse := '{"getThreadPoolName": "Metodo getThreadPoolName nao foi executado"}'
EndIf
 
oRest:setResponse(cResponse)
 
 
Return .T.
