#include "tlpp-core.th"
#include "tlpp-rest.th"
 
@Get("/documentation/getThreadPoolServiceName")
User Function fGetThreadPoolServiceName()
 
Local cResponse := ""
Local cRet      := ""
 
cRet := oRest:getThreadPoolServiceName()
 
If (ValType(cRet) == 'C')
    cResponse := '{"getThreadPoolServiceName": "' + cRet + '"}'
Else
    cResponse := '{"getThreadPoolServiceName": "Metodo getThreadPoolServiceName nao foi executado"}'
EndIf
 
oRest:setResponse(cResponse)
 
 
Return .T.
