#include "tlpp-core.th"
#include "tlpp-rest.th"
 
/* --------------------------------------------- */
@Delete("examples/function/delete/query/user")
User Function examplesFunctionDeleteQuery()
Local cJson := ""
Local jQuery
 
jQuery := JsonObject():New()
jQuery := oRest:getQueryRequest()
 
If (jQuery <> Nil)
    cJson := '[ {"description": "examplesFunctionDeleteQuery successfully executed, parameter received: ' + jQuery['user'] + '"} ]'
Endif
 
 
Return oRest:setResponse(cJson)
