#include "tlpp-core.th"
#include "tlpp-rest.th"
 
/* --------------------------------------- */
@Get("examples/function/get/path/user/:user")
User Function examplesFunctionGetPath()
Local cJson := ""
Local jPath
 
jPath := JsonObject():New()
jPath := oRest:getPathParamsRequest()
 
If (jPath <> Nil)
    cJson := '[ { "description": "functionExamplesGetPath successfully executed, parameter received: ' + jPath['user'] +'"} ]'
Endif
 
 
 
Return oRest:setResponse(cJson)
