#include "tlpp-core.th"
#include "tlpp-rest.th"
 
@Get("/documentation/getRetCodResponse")
User Function fGetRetCodResponse()
 
Local cResponse := ""
Local nRet      := -1
 
oRest:setStatusCode(201)
 
nRet := oRest:getRetCodResponse()
 
If (ValType(nRet) == 'N' .And. nRet >= 0)
    cResponse := '{"StatusLidoDaMemoria": "' + cValToChar(nRet) + '"}'
Else
    cResponse := '{"Erro": "metodo de leitura falhou"}'
EndIf
 
oRest:setResponse(cResponse)
 
 
Return .T.
