#include "tlpp-core.th"
#include "tlpp-rest.th"
 
@Get("/documentation/getHeaderRequest")
User Function fGetHeaderRequest()
 
Local cResponse := ""
Local jHeader
 
jHeader := oRest:getHeaderRequest()
 
If (ValType(jHeader) == 'J')
    cResponse := '{"Header":['
    cResponse += jHeader:toJson()
    cResponse += ']}'
Else
    cResponse := '{"getHeaderRequest": "método getHeaderRequest não foi executado"}'
EndIf
 
oRest:setResponse(cResponse)
 
 
Return .T.
